### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by k0fi** [kurrik/twittergo-examples#4]
Hello, 

I get this error few seconds after  I strat to track this combination of strings:
`"a,b,c,d,e,f"`

I'm using  twittergo-examples/stream/main.go with no modifications. 

```
goroutine 39 [running]:
github.com/kurrik/twittergo.Tweet.Id(0xc4205ba6c0, 0x34)
	/home/me/go/src/github.com/kurrik/twittergo/models.go:325 +0x168
main.filterStream.func1(0xc4201a20c0)
	/home/me/go/src/sandbox/main.go:173 +0x1aa
created by main.filterStream
	/home/me/go/src/sandbox/main.go:168 +0x193
exit status 2

```
Why this happens? 
How can I fix it?

**Comment by kurrik** [comment]
I wasn't able to reproduce, but https://github.com/kurrik/twittergo/commit/f4ede9427aea6f8f5db538f5b04c2c4a106939bb does fix a deserialization issue in cases where a string is expected but the decoded json object returns a different type, which I think is what is going on here (although there's likely another masked problem, since all Tweets should have valid IDs!)
